on:
  workflow_dispatch:
  schedule:
    - cron: '*/45 */3 */7 * *'


jobs:

  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: fu1ny2t-3es/ym1202173-ca4sk5ll@cron
        with:
          token: ${{ secrets.token }}
